### ISSUE TITLE
change the @master to @v0 of google-github-action in github/workflow

### ISSUE THREAD

**Issue by easa** [ljvmiranda921/cv#35]
"Do not pin this action to @master, use @v0 instead. We are going to rename the branch to main in 2022 and this will break existing workflows" [google-github-actions](https://github.com/google-github-actions/setup-gcloud)

**Comment by ljvmiranda921** [comment]
Hey @easa , thanks for this issue! Will update my workflow soon. Thanks again and happy new year :)

**Comment by easa** [comment]
@ljvmiranda921 No problem and happy new year 🎄🎉
I actually looked up your repo to set up my template for collaborating on an article with latex on Github. Thank you for writing the post and having this repo public.
